import { CardCustomization, TemplateDefinition } from './types';

export const TEMPLATE_DEFINITIONS: TemplateDefinition[] = [
  // --- PLATFORM INTRODUCTION POSTS ---
  {
    id: 'platform-intro',
    title: 'Farzandly nima?',
    shortDesc: 'Platforma manifestosi va 3 ta asosiy ustun',
    hookPreview: 'Farzand tarbiyasida o‘zingizni yolg‘iz his qilyapsizmi?',
    iconName: 'Compass',
    badge: 'Tanishtiruv',
    category: 'intro',
  },
  {
    id: 'nega-farzandly',
    title: 'Nega aynan Farzandly?',
    shortDesc: 'Ota-onalarning 3 katta dardi va aniq yechim',
    hookPreview: 'Mukammal ota-ona bo‘lish shart emas, hushyor bo‘lish kifoya',
    iconName: 'HelpCircle',
    badge: 'Muammo & Yechim',
    category: 'intro',
  },
  {
    id: 'feature-showcase',
    title: 'Platformada nimalar bor?',
    shortDesc: 'Darslar, audio ertaklar, simulyator va reyting',
    hookPreview: 'Mobil ilovadek qulay, ustozdek mehribon',
    iconName: 'Sparkles',
    badge: 'Funksiyalar',
    category: 'intro',
  },

  // --- SPECIFIC PARENTING TOPICS ---
  {
    id: 'mehrli-tarbiya',
    title: 'Mehrli Tarbiya',
    shortDesc: 'Gentle Parenting vs Baqirish va Tantrum',
    hookPreview: 'Bolaga baqirmasdan gap uqtirishning 3 qoidasi',
    iconName: 'HeartHandshake',
    badge: '2-7 yosh',
    category: 'parenting',
  },
  {
    id: 'ekran-vaqti',
    title: 'Ekran Vaqti',
    shortDesc: 'Dopamin inqirozi va smartfonni tinch cheklash',
    hookPreview: 'Smartfonni yig‘i-sig‘isiz cheklash mumkinmi?',
    iconName: 'Smartphone',
    badge: 'Odatlar',
    category: 'parenting',
  },
  {
    id: 'gamification',
    title: 'Duolingo for Parents',
    shortDesc: 'Mikro-ta’lim, streak, XP va mini-test',
    hookPreview: 'Farzand tarbiyasi — qalin kitoblar emas, 5 daqiqalik odat',
    iconName: 'Flame',
    badge: 'Gamifikatsiya',
    category: 'parenting',
  },
  {
    id: 'hikmat-va-ilm',
    title: 'Hikmat va Ilm',
    shortDesc: 'Islomiy qadriyatlar va Garvard neyropsixologiyasi',
    hookPreview: 'Go‘zal odob — eng katta sarmoya',
    iconName: 'Sparkles',
    badge: 'Qadriyat',
    category: 'parenting',
  },
];

export const INITIAL_CUSTOMIZATION: CardCustomization = {
  template: 'platform-intro',
  theme: 'sage-classic',
  ageCategory: 'Barcha yoshlar',
  showLogo: true,
  showQrCode: true,
  showSlideNumber: true,
  slideNumber: '1/5',
  footerHandle: '@farzandly.uz',
  footerTagline: 'Har kuni 5 daqiqa',

  platformIntro: {
    hook: 'Farzand tarbiyasida o‘zingizni yolg‘iz his qilyapsizmi?',
    subtitle: 'Bolaga baqirishdan charchadingizmi? Farzandly — zamonaviy neyropsixologiya va islomiy qadriyatlarni birlashtirgan ilk mikro-ta’lim platformasi.',
    categoryTag: 'PLATFORMA BILAN TANISHUV',
    pillar1Title: '1. Har kuni atigi 5 daqiqa',
    pillar1Desc: 'Qalin kitoblar o‘qishga vaqt yo‘qmi? Biz sizga har kuni bitta amaliy, sinalgan va hayotiy qadamni beramiz.',
    pillar1Tag: 'Mikro-ta’lim',
    pillar2Title: '2. Ilm va Fitrat uyg‘unligi',
    pillar2Desc: 'Garvard universiteti bolalar psixologiyasi va 14 asrlik sahih islomiy tarbiya odoblari bitta tizimda mujassam.',
    pillar2Tag: 'Ikki qanot',
    pillar3Title: '3. Duolingo uslubidagi gamifikatsiya',
    pillar3Desc: 'Zerikarli ma’ruzalar emas! Kunlik streak, XP ballari va vaziyatli mini-testlar orqali odat shakllantiring.',
    pillar3Tag: 'O‘yinlashtirish',
    targetAges: '0-2, 3-5, 6-9, 10-13 va 14+ yosh toifalari bo‘yicha ajratilgan',
    ctaText: 'Hoziroq farzandly.uz saytiga kiring va birinchi darsni boshlang!',
  },

  negaFarzandly: {
    hook: 'Mukammal ota-ona bo‘lish shart emas, hushyor bo‘lish kifoya',
    subtitle: 'Bugungi zamonaviy ota-onalarning 3 ta eng katta dardi va Farzandly taklif qiladigan aniq yechim:',
    categoryTag: 'NEGA AYNAN FARZANDLY?',
    prob1Title: 'Vaqt tanqisligi',
    prob1Text: 'Charchoq va bandlik sabab qalin kitoblarni o‘qishga vaqt topilmaydi.',
    sol1Title: 'Farzandly Yechimi',
    sol1Text: 'Kuniga 5 daqiqalik lo‘nda audio va vizual darslar orqali tez o‘rganish.',
    prob2Title: 'Qarama-qarshi ma’lumotlar',
    prob2Text: 'Internetdagi minglab maslahatlar bir-biriga zid va asossiz.',
    sol2Title: 'Farzandly Yechimi',
    sol2Text: 'Faqat fitrat, islomiy odob va ilmiy psixologiyaga tayangan toza bilim.',
    prob3Title: 'Aybdorlik hissi',
    prob3Text: 'Bolaga asabiylashib baqirib qo‘yib, o‘zimizni yomon ota-ona deb o‘ylash.',
    sol3Title: 'Farzandly Yechimi',
    sol3Text: 'Injiqlik va tantrum daqiqalarida o‘zingizni tutish bo‘yicha tayyor skriptlar.',
    takeaway: 'Farzandly — sizning cho‘ntagingizdagi xotirjam va mehribon tarbiya murabbiyi.',
  },

  featureShowcase: {
    hook: 'Mobil ilovadek qulay, ustozdek mehribon',
    subtitle: 'Farzandly platformasiga obuna bo‘lganingizda sizga ochiladigan boy imkoniyatlar:',
    categoryTag: 'PLATFORMA IMKONIYATLARI',
    feat1Title: '50+ Interaktiv Darslar',
    feat1Desc: 'Har biri 3-5 daqiqalik, amaliy vaziyatlar va mashqlar bilan boyitilgan.',
    feat1Badge: 'Mikro-kurslar',
    feat2Title: 'Sara Ibratli Ertaklar',
    feat2Desc: 'Bolalar olami — bolangiz tinglashi uchun mehrli va axloqiy audio ertaklar.',
    feat2Badge: 'Bolalar uchun',
    feat3Title: 'Vaziyatlar Simulyatori',
    feat3Desc: 'Do‘konda injiqlik, telefon talashish — to‘g‘ri javobni tanlab XP to‘plang.',
    feat3Badge: 'Interaktiv',
    feat4Title: 'Streak & Darajalar',
    feat4Desc: 'Ota-onalik kundaligi, doimiy odat va reyting ko‘rsatkichi.',
    feat4Badge: 'Motivatsiya',
    bottomPromo: '🎁 Birinchi 3 ta dars barcha ota-onalar uchun mutlaqo bepul!',
  },

  mehrliTarbiya: {
    hook: 'Bolaga baqirmasdan gap uqtirishning 3 qoidasi',
    subtitle: 'Baqirish bola miyasida faqat qo‘rquv va himoya zonasini uyg‘otadi. Mehr va qat’iyat bilan ta’sir qilish yo‘li:',
    categoryTag: 'MEHRLI TARBIYA',
    step1Title: '1. Ko‘z darajasiga tushing',
    step1Desc: 'Balanddan buyruq bermang. Bola oldida cho‘qqayib, uning ko‘zlariga mehr bilan boqing. Bu bolada xavfsizlik va eshitilish hissini uyg‘otadi.',
    step1Tag: 'Neyropsixologiya',
    step2Title: '2. Hissini tan oling',
    step2Desc: '«Jahling chiqyapti, tushunaman... O‘yinchoqni bergisi kelmayapti». Hissiyot inkor qilinmasa, bolaning agressiv qarshiligi so‘nadi.',
    step2Tag: 'Empatiya',
    step3Title: '3. Qat’iy chegara qo‘ying',
    step3Desc: 'Baqirmang, lekin bo‘shashmang ham. «Lekin urish yoki sindirish mumkin emas». Qat’iy, lekin sokin ovoz — ota-onaning eng qudratli quroli.',
    step3Tag: 'Qat’iyat',
    comparisonWrong: 'Baqirish: bola faqat qo‘rqadi, xulosani tushunmaydi',
    comparisonRight: 'Sokin muloqot: bola ichki mas’uliyatni his qiladi',
    takeaway: 'Bolalar biz nima deganimizni emas, o‘zimizni qanday tutganimizni o‘rganadilar.',
  },

  ekranVaqti: {
    hook: 'Smartfonni yig‘i-sig‘isiz cheklash mumkinmi?',
    subtitle: 'Telefonni to‘satdan tortib olish — bolada kuchli dopamin shokini uyg‘otadi. Buning o‘rniga 3 ta sinovdan o‘tgan yechim:',
    categoryTag: 'EKRAN VAQTI',
    alt1Title: '1. Taymer bilan oldindan ogohlantirish',
    alt1Desc: '«Hoziroq ber!» deb emas, «Yana 5 daqiqadan so‘ng taymer jiringlaydi, multfilm tugaydi» deb birga belgilang. Kutilmagan uzilish bo‘lmaydi.',
    alt1Badge: '5 daqiqa oldin',
    alt2Title: '2. «Dopamin ko‘prigi» (Ertak yoki birgalikda o‘yin)',
    alt2Desc: 'Ekran o‘chgach darhol bo‘shliq qolmasin. Rangli qalamlar, sevimli ertak yoki kichik birgalikdagi o‘yin taklif qiling.',
    alt2Badge: 'Muqobil quvonch',
    alt3Title: '3. Tanlash imkoniyatini bering',
    alt3Desc: '«O‘chir» degan buyruq o‘rniga: «Xohlasang, birga lego quramiz yoki rasmli kitob ko‘ramiz». Bola o‘zini boshqaruvda his qilsin.',
    alt3Badge: 'Avtonomiya',
    recommendation: 'JSST va Pediatriya akademiyasi tavsiyasi: 2 yoshgacha ekran 0 daqiqa, 3-5 yosh oralig‘ida kuniga maksimum 45 daqiqa sifatli kontent.',
    takeaway: 'Ekrandan ajratish — taqiq emas, yangi qiziqarli mashg‘ulotga taklif bo‘lishi lozim.',
  },

  gamification: {
    hook: 'Farzand tarbiyasi — qalin kitoblar emas, 5 daqiqalik odat',
    subtitle: 'Farzandly — ota-onalar uchun ilk o‘yinlashtirilgan mikro-ta’lim platformasi. Har kuni bitta kichik amaliy qadam:',
    categoryTag: 'MIKRO-TA’LIM',
    streakDays: 7,
    streakText: 'kunlik odat ketma-ketligi',
    xpPoints: 150,
    levelTitle: 'Hushyor ota-ona',
    levelNumber: 3,
    lesson1Title: 'Bolani eshitish siri',
    lesson1Status: 'Tugallandi',
    lesson2Title: 'Injiqlik daqiqalarida xotirjamlik',
    lesson2Status: 'Hozirgi dars',
    lesson3Title: 'Uxlash odatini shakllantirish',
    lesson3Status: 'Qulflangan',
    quizQuestion: 'Bola do‘konda o‘yinchoq talab qilib qattiq yig‘lasa, birinchi qadamingiz nima?',
    quizWrongAnswer: 'Darhol jahlingiz chiqib, do‘kondan sudrab olib chiqish',
    quizRightAnswer: 'Yoniga o‘tirib, xotirjam quchoqlash va hissiyotini tan olish (+20 XP)',
    takeaway: 'Katta o‘zgarishlar qalin kitoblar bilan emas, har kungi 5 daqiqalik sabr va bilim bilan yuz beradi.',
  },

  hikmatVaIlm: {
    hook: 'Go‘zal odob — eng katta sarmoya',
    subtitle: '14 asrlik islomiy hikmat va bugungi zamonaviy neyropsixologiya aynan bir haqiqatda birlashadi:',
    categoryTag: 'HIKMAT VA ILM',
    hadithTitle: 'Sahih Hadis & Islomiy Tarbiya',
    hadithText: '«Hech bir ota o‘z farzandiga go‘zal odobdan afzalroq narsa bera olmaydi.»',
    hadithSource: 'Imom Termiziy rivoyati',
    hadithDetail: 'Payg‘ambarimiz (s.a.v.) yosh bolalar bilan gaplashganda ularning qo‘lidan ushlab, butun vujudlari bilan o‘girilib, mehr va ehtirom bilan tinglaganlar.',
    scienceTitle: 'Zamonaviy Bolalar Neyropsixologiyasi',
    scienceText: 'Garvard universiteti tadqiqotlari tasdiqlaydi: Bola ota-onadan to‘liq ko‘z muloqoti va empatiya olganda, miyaning iroda hamda o‘zini boshqarish markazlari ancha tez rivojlanadi.',
    scienceSource: 'Center on the Developing Child (Harvard)',
    scienceDetail: 'Tazyiqsiz, mehr va barqaror qoidalar asosidagi muhit bolada mustahkam xavfsiz bog‘lanish (secure attachment) shakllantiradi.',
    synthesisTitle: 'Xulosa va Amaliy Ibrat',
    synthesisText: 'Farzandga baqirib qo‘rqitish emas, go‘zal ibrat va sabr bilan yondashish — eng buyuk sunnat va eng kuchli ilmiy tarbiyadir.',
  },
};
